### ISSUE TITLE
Different translation in Arabic for different numbers

### ISSUE THREAD

**Issue by AA0000-33** [whatpulse/client-translations#16]
When you say "1 item" in Arabic, you say "عنصر", you don't say "1 عنصر", when you say "2 items" you say "عنصرين", when you say "3-10 items" you say "3-10 عناصر", when you say "11-99… items" you say "11-99 عنصراً", and when you say "100, 1000, 10000, … items" you say "100, 1000, 10000, … عنصر"
Just like when you add "s" to "item" when you have more than 1 item in English, and remove it when you say "100 item", there's a different variant of the word in Arabic for different numbers, so, the current translation template should have 5 different strings for each word for these numbers:
- 1
- 2
- 3-10 (single numbers)
- 11-19 (composite numbers) and 20-99 (joined numbers, which are 1-9 (single numbers), 11-19 (composite numbers), and 20, 30, … (decades) joined together), so basically 11-99
- 100, 2000, 30000, … (centuries)

So in a number like "9212490981 items", the last two digits are joined numbers, the number 1 which is now a single number since it's no longer just 1 or 2, and the number 80 which is a decade, so it would use the word for the joined numbers, "عنصراً"
But in a number like "1027410902 items", the last two digits are 02, so we use the word for centuries, "عنصر", but only with 01 and 02, if it's 03 or something else, we use the word that applies to it, in this case, single numbers, "عناصر"

This applies to words such as "1 day", "1 hour", "1 minute", "1 restart", but it doesn't apply to words like "1 MB", because this word is transliterated, meaning it says the same thing in English using similar sounding letters in Arabic, so it only uses one word for all numbers, therefore it's better to apply this to all words and let us choose which words use it and which words just have the same word in all 5 variants of the word

I'm sure there are other languages that use this too, maybe for even more variants of numbers, but in Arabic, it's like this.

Translated examples:
1 item: عنصر
2 items: عنصرين
7 items: 7 عناصر
37 items: 37 عنصراً
102 items: 102 عنصر
107 items: 107 عناصر
827 items: 827 عنصراً
100007 items: 100007عناصر

**Comment by smitmartijn** [comment]
While I appreciate the thorough explanations you've given here, I'm closing this issue because there's been no requests for this, it seems WhatPulse isn't used that much in Arabic countries.
