### ISSUE TITLE
Facts translation - AR

### ISSUE THREAD

**Issue by smitmartijn** [whatpulse/client-translations#23]
Hi @AA0000-33,

The latest translation template now also includes the facts and I was hoping you could translate them like you did with the rest of the client? It's [only] 31 sentences, it should hopefully be quick. 😄 

Thanks!

**Comment by AA0000-33** [comment]
Hi @smitmartijn,

Yea sure no problem, I'll do it when I have free time for it. 🙂

**Comment by AA0000-33** [comment]
@smitmartijn [all done](https://github.com/whatpulse/client-translations/pull/34) 🙂

**Comment by smitmartijn** [comment]
Awesome, thanks!
