### ISSUE TITLE
Facts translation - SV

### ISSUE THREAD

**Issue by smitmartijn** [whatpulse/client-translations#24]
Hi @Remlej9,

The latest translation template now also includes the facts and I was hoping you could translate them like you did with the rest of the client? It's [only] 31 sentences, it should hopefully be quick. 😄 

Thanks!

**Comment by Remlej9** [comment]
@smitmartijn Of course! I will do it as soon as I can 😄

**Comment by smitmartijn** [comment]
Closed with https://github.com/whatpulse/client-translations/pull/36 🎉
