### ISSUE TITLE
Facts translation - BG

### ISSUE THREAD

**Issue by smitmartijn** [whatpulse/client-translations#25]
Hi @Radotornado,

The latest translation template now also includes the facts and I was hoping you could translate them like you did with the rest of the client? It's [only] 31 sentences, it should hopefully be quick. 😄 

Thanks!

**Comment by Radotornado** [comment]
Of course, I'll do it this week. :)

**Comment by smitmartijn** [comment]
Closed with https://github.com/whatpulse/client-translations/pull/35 🥳
