### ISSUE TITLE
Facts translation - zh_cn

### ISSUE THREAD

**Issue by smitmartijn** [whatpulse/client-translations#28]
Hi @Geno1024,

The latest translation template now also includes the facts and I was hoping you could translate them like you did with the rest of the client? It's [only] 31 sentences, it should hopefully be quick. 😄 

Thanks!

**Comment by Geno1024** [comment]
OK.

Sorry for forgotten #12.

I will be back quickly.

**Comment by Geno1024** [comment]
Did you missed a `<b>` at `facts.cpp:369`?

> `You've typed the most on <b>%VAR2:date%</b> (%VAR1:int% keys!)`

I am not sure whether the `%VAR1:int%` is expected to be bold too.

**Comment by Geno1024** [comment]
#32

**Comment by smitmartijn** [comment]
Looks good to me, thanks! And the missing <b> there is intentional - otherwise it's too much bold. 😄
