### ISSUE TITLE
Facts translation - FR

### ISSUE THREAD

**Issue by smitmartijn** [whatpulse/client-translations#30]
Hi @UBrainDev,

The latest translation template now also includes the facts and I was hoping you could translate them like you did with the rest of the client? It's [only] 31 sentences, it should hopefully be quick. 😄 

Thanks!

**Comment by UBrainDev** [comment]
Hi,

Sure, I'll start working on it!

**Comment by smitmartijn** [comment]
Closed with https://github.com/whatpulse/client-translations/pull/33
