### ISSUE TITLE
Missing translation entries

### ISSUE THREAD

**Issue by dix** [whatpulse/client-translations#48]
Hi,

I'm currently working on fixing the _\_fr_ translation file and it seems that some entries are missing, meaning it's impossible to translate some labels.

Here are the ones I noticed as of now.

- _Inputs_ tab, _Mouse_ sub-tab > _Button Clicks_ and _Scrolls_ titles

![image](https://github.com/whatpulse/client-translations/assets/11793160/fc72bed0-abd9-44c1-8666-2274b031a1a5)

- _Inputs_ tab, _Input History_ sub-tab > _Keys_ and _Clicks_ legends

![image](https://github.com/whatpulse/client-translations/assets/11793160/22736c1b-8443-49bf-b8e8-99ad5be78113)

- _Uptime_ tab, _Reboot Calendar_ sub-tab > Basically all the dates

![image](https://github.com/whatpulse/client-translations/assets/11793160/038f370e-98e0-4413-abbd-5852201dd37e)

- _Settings_ tab, _General_ sub-tab > _Run as Administrator_ item

![image](https://github.com/whatpulse/client-translations/assets/11793160/1b6c5ffe-d18d-4b72-a742-fad63d844174)

- _Settings_ tab, _Geek Window_ sub-tab > The _Edit me_ default text for a new label

![image](https://github.com/whatpulse/client-translations/assets/11793160/ef83fe2b-abc2-4e31-9abf-2fe2710bfacd)

**Comment by smitmartijn** [comment]
Hi @dix - thanks for pointing those out. I've updated the client beta to fix most of these. One exception being the Uptime tab, those are translated to other languages with the built in libraries. That's why there's a call-out to refresh the window when you change the language, to refresh those built-in strings.

**Comment by dix** [comment]
Hi @smitmartijn 

Thanks for the fixes and for your explanations!

One last question regarding the dev process since you're talking about a beta version in your comment : is it still relevant to try and fix the current version of the translation files or is it preferable to wait for the new ones which will come once the beta is released?

For instance, some translation entries in the current version of the _.ts_ files could be removed in the next release?

**Comment by smitmartijn** [comment]
@dix  There isn't a separate release for language files alone, it'll always be paired with a software release. Typically there won't be any removals, maybe only reshuffles (from 1 section to another section), but I take care of those.

I pushed these updates to this repository just now, so you should see the fixes now. 😄
