### ISSUE TITLE
Do I need to preserve hotkey?

### ISSUE THREAD

**Issue by Geno1024** [whatpulse/client-translations#6]
For example, 
```xml
    <message>
        <location filename="../interface/AccountTab.cpp" line="132"/>
        <source> &amp;View Online Stats</source>
        <translation> Translation</translation>
    </message>
```

This source using a "V" as hotkey. Do I need to preserve a "V" for `&amp;V`, for keeping a "hotkey conservation" between different languages?

In (at least Simplified) Chinese, there is a common solution for this: translate in Chinese as usual, then add a parenthesis for adding the hotkey. For example `&File` will be translated as `文件(&F)`. But, at this time all other languages didn't keep the "hotkey conservation", and README isn't clear to this, so I am not sure about how to handle this.

---

A phenomenon of Information Cocoons?

**Comment by smitmartijn** [comment]
Hi @Geno1024,

First off, thanks for looking into the Chinese translation - that would be an awesome addition. Secondly, the hotkeys are not that necessary. I've discovered most people do not use them. For languages with characters like Chinese, I'd suggest keeping it as simple as possible and not add them.
