### ISSUE TITLE
Planning to add RTL language

### ISSUE THREAD

**Issue by salamwaddah** [whatpulse/client-translations#8]
Hey, I pulse since 2015 and just realized this repo. Great work!

I want to contribute Arabic but it's like many other languages a RTL language (right to left) do you think that will break the layout of the app?

**Comment by smitmartijn** [comment]
Hi Salam, that's a good point. It won't break the app, but it might put some phrases into a confusing state. There are some layouts that are specifically designed with left to right bias. I'd say go ahead and we can see if it even makes sense. I've added researching how to cover RTL on my to do, I'm sure there are ways to allow it.

**Comment by smitmartijn** [comment]
While I appreciate the thorough explanations you've given here, I'm closing this issue because there's been no requests for this, it seems WhatPulse isn't used that much in Arabic countries.
